# Machine Learning Course - Day 4

Primero que nada, importaremos la libreria numpy, previamente instalada y crearemos un arreglo para ver que se haya instalado correctamente

In [1]:
import numpy
arreglo = numpy.array([1,2,3,4,5])

In [2]:
type(arreglo)

numpy.ndarray

In [3]:
arreglo[1]

2

En dado caso de que solamente quisieramos utilizar un solo metodo de la libreria podriamos especificarlo en el import, si embargo, librerias como numpy siempre se importan completas ya que siempre se usa mas de un metodo

In [6]:
from numpy import array

# Muchas veces se acostumbra poner un alias a la importacion
import numpy as np

Es importante especificar las dimensiones que tendra nuestro arreglo utilizando los corchetes, de esta forma la libreria podria crear nuestro arreglo para poder usarlo

In [7]:
arreglo_unidimencional = np.array([1,2,3,4,5])

# Para este caso especifico se tiene un arreglo, cuyo contenido son 2 arreglos, esto hace que este sea bidimencional
arreglo_bidimencional = np.array([[1,2,3],[4,5,6]])

In [8]:
print(arreglo_bidimencional)

[[1 2 3]
 [4 5 6]]


Si buscaramos saber el tamaño de nuestro arreglo, usaremos la propiedad ndim

In [10]:
print(arreglo_bidimencional.ndim)

2


Aunque tambien podemos usar la funcion len() para saber la cantidad de valores en el arreglo y poder acceder a las posiciones del arreglo

In [13]:
arreglo_muchos_valores = np.array([3,4,5,12,34,4,5,2,4,])
for i in range(len(arreglo_muchos_valores)):
    print(arreglo_muchos_valores[i])

3
4
5
12
34
4
5
2
4


Para acceder a la lista a la inversa, usamos valores negativos

In [17]:
print("El ultimo valor es: " + str(arreglo_muchos_valores[-1]))
print("El penultimo valor es: " + str(arreglo_muchos_valores[-2]))

El ultimo valor es: 4
El penultimo valor es: 2


En el caso de querer acceder a un arreglo bidimencional debemos usar las coordenadas del valor que buscamos, esto lo podemos hacer con ciclos anidados o bien accediendo directamente

In [18]:
print(arreglo_bidimencional[0,0])

1


Tambien podemos hacer algo llamado Slicing, lo cual consiste en seleccionar especificamente entre que secciones del arreglo estaremos iterando

In [19]:
print(arreglo_muchos_valores[2:5])

[ 5 12 34]


Si quieres recorrer el arreglo por medio de saltos, puedes mandar un tercer parametro separado por dos puntos

In [20]:
print(arreglo_muchos_valores[0:-1:2])

[ 3  5 34  5]


# Typos de datos 

En python tenemos una gran cantidad de tipos de datos, especificamente para los tipos de datos que reconocen los arreglos de python, utilizaremos el metodo dtype

In [27]:
arrego_tipo_dato = np.array([1,2,3,4,5])
print(arrego_tipo_dato.dtype)

arrego_tipos_datos = np.array(["oso",True,1])
print(arrego_tipos_datos.dtype)

int32
<U11


Para copiar un arreglo podemos utilizar la funcion copy()

In [28]:
arreglo_uno = np.array([1,2,3,4,5])
arreglo_copia = arreglo_uno.copy()

print(arreglo_uno)
print(arreglo_copia)

[1 2 3 4 5]
[1 2 3 4 5]
