# Ejercicios Numpy
**Nombre:** tu nombre

**Expediente:** tu expediente

Realiza los ejecicios que se indican en este notebook para practicar tu uso de numpy

**Ejercicios**

1.   Crea un arreglo con los siguientes valores: `10, 15, 20, 25, 30, 35, 40`










In [3]:
import numpy as np

primer_arreglo = np.array([10,15,20,25,30,35,40])
print(primer_arreglo)

[10 15 20 25 30 35 40]


2.   Crea un arreglo que contenga los valores: `1,4,9,6,3` en una 3da dimension





In [4]:
segundo_arreglo = np.array([[[1,4,9,6,3]]])
print(segundo_arreglo)

[[[1 4 9 6 3]]]




3.   Verifica por medio de codigo que el arreglo escrito en el ejercicio anterior corresponda a una 3ra dimension.



In [6]:
print(segundo_arreglo.ndim)

3


4.   Accede e imprime el 5to elemento del siguiente arreglo  
```
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
```
(Deberas crear el arreglo y ejecutarlo)



In [9]:
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
print(arreglo[4])

4


5.   Como puedes imprimir el numero 23 del arreglo
```
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
```




In [10]:
print(arreglo[-3])

23


6.   Como puedes imprimir el numero 23 del arreglo
```
arreglo = np.array([[1,6,9,3,4,6],[8,5,10,23,5,4]])
```
(Deberas crear el arreglo y ejecutarlo)


In [11]:
arreglo = np.array([[1,6,9,3,4,6],[8,5,10,23,5,4]])
print(arreglo[1][-3])

23


7.   Como puedes imprimir el ultimo elemento del arreglo
```
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
```

In [12]:
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
print(arreglo[-1])

4


8.   Genera un nuevo arreglo a partir del que se muestra, en el que incluyas los elementos de la posicion 3 (incluyendolo, hasta la posicion 9 (sin incluirla)
```
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
```

In [16]:
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
print(arreglo[3-1:9-1])

[9 3 4 6 8 5]


9. Genera un nuevo arreglo a partir del siguiente, con cada 2do elemento del arreglo
```
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
```

In [18]:
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
arreglo2 = arreglo[1::2]
print(arreglo)
print(arreglo2)

[ 1  6  9  3  4  6  8  5 10 23  5  4]
[ 6  3  6  5 23  4]


10. Muestra el tipo de los datos contenidos en el siguiente arreglo:


```
arreglo = np.array([6,2,3,9,4])
```



In [19]:
arreglo = np.array([6,2,3,9,4])
print(arreglo.dtype)

int32


11. Especifica desde la declaracion del arreglo que el tipo de dato para que sea String
```
arreglo = np.array([6,2,3,9,4])
```

In [20]:
arreglo = np.array([6,2,3,9,4], dtype = str)
print(arreglo.dtype)

<U1


12. Declara el siguiente arreglo y posteriormente indica que sea de tipo `integer`

```
arreglo = np.array([6.3,2.5,3.0,9.1,4.9])
```

In [23]:
arreglo = np.array([6.3,2.5,3.0,9.1,4.9], dtype = int)
print(arreglo.dtype)

int32


12. Redacta la diferencia entre copiar un arrego con el comando copy() y el comando view()
¿Que ventaja crees que tiene view()?

Usando copy crearemos un nuevo arreglo sin dependencia del original, con view, por el contrario crearemos una referencia al primero y cuando sea modificado, el nuevo sera modificado tambien

13. Indica cuantos elementos tiene el siguiente arreglo:

```
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
```

In [24]:
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
print(arreglo.size)

12


14. Indica cuantos elementos tiene el siguiente arreglo:
```
arreglo = np.array([[1,6,9,3,4,6],[8,5,10,23,5,4]])
```

In [25]:
arreglo = np.array([[1,6,9,3,4,6],[8,5,10,23,5,4]])
print(arreglo.size)

12


14. Redimensiona el siguiente arreglo de 1-D a 2-D con 3 subarreglos y que contengan 4 elementos en cada segmento:

```
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
```

In [26]:
arreglo = np.array([1,6,9,3,4,6,8,5,10,23,5,4])
arreglo.reshape(3,4)

array([[ 1,  6,  9,  3],
       [ 4,  6,  8,  5],
       [10, 23,  5,  4]])

15. Redimensiona el siguiente arreglo de 2-D a 1-D:

```
arreglo = np.array([[1,6,9,3,4,6],[8,5,10,23,5,4]])
```

In [27]:
arreglo = np.array([[1,6,9,3,4,6],[8,5,10,23,5,4]])
arreglo.flatten()

array([ 1,  6,  9,  3,  4,  6,  8,  5, 10, 23,  5,  4])